feat: Addition of new public theme tokens.
cloudscape-design/components pull request #1061
Opened 2023-05-04 20:59 UTC by DaemonCahill

### Description

This PR adds several new tokens to the public theme API in order to adjust the presentation of the `AppLayout`, `ContentLayout`, and `TopNavigation` components.

### How has this been tested?

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-05 10:23 UTC, stirache requested changes

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The background color ot the app layout toggle button when it is active.',
Suggested rephrase: 'The background color of the app layout toggle button when it's active.'

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The default background color ot the app layout toggle button.',
Typo: 'The default background color _of_ the app layout toggle button.'

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The background color of the app layout toggle button when it is hovered.',
Suggested rephrase: 'The background color of the app layout toggle button on hover.'

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The background color of the app layout toggle button when it is selected and active.',
Replace "it is" with "it's"

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The default background color of the app layout toggle button when it is selected.',
Replace "it is" with "it's"

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The background color of the app layout toggle button when it is selected and hovered.',
Suggested rephrase: 'The background color of the app layout toggle button when it's selected and on hover.'

2023-05-05 10:23 UTC, stirache commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: 'The color of clickable elements in their active state. For example: tabs, and icons.',
Remove comma after "tabs"

2023-05-09 08:03 UTC, stirache submitted a review, later dismissed

2023-05-09 10:59 UTC, gethinwebster requested changes

2023-05-09 10:59 UTC, gethinwebster commented on style-dictionary/visual-refresh/metadata/colors.ts
> +    description: "The background color of the app layout toggle button when it's selected and on hover.",
"selected and on hover" doesn't read right to me, what do you think @stirache ?

2023-05-09 16:22 UTC, gethinwebster approved these changes

2023-05-09 18:15 UTC, merged