Improve unit test APIs for Input & TextArea ElementWrappers by exposing getters for value property
cloudscape-design/components pull request #1062
Opened 2023-05-05 02:39 UTC by ajchili

### Description

**Include a summary of the changes and the related issue:** This change introduces getters for `Input` & `TextArea` ElementWrappers to support string validation in unit tests.

**Also include relevant motivation and context:** This was motivated by an internal AWS discussion.

Related links, issue #, if available: n/a

### How has this been tested?

**How did you test to verify your changes?** I added unit tests.

**How can reviewers test these changes efficiently?** Running the unit tests locally or validating via an integration test.

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-08 12:07 UTC, rubencarvalho commented
Thank you for opening the PR, I'll bring it up with the team and update you 👍

2023-05-08 15:23 UTC, rubencarvalho requested changes

2023-05-10 00:12 UTC, ajchili commented
`Build, lint and test / deploy / deploy (pull_request)` is [failing](https://github.com/cloudscape-design/components/actions/runs/4921259436/jobs/8798162320?pr=1062) due to credential issues. Can the Cloudscape team please assist with remediating this test failure?

2023-05-15 08:53 UTC, rubencarvalho approved these changes

2023-05-15 08:53 UTC, rubencarvalho approved these changes

2023-05-15 08:55 UTC, rubencarvalho commented
> `Build, lint and test / deploy / deploy (pull_request)` is [failing](https://github.com/cloudscape-design/components/actions/runs/4921259436/jobs/8798162320?pr=1062) due to credential issues. Can the Cloudscape team please assist with remediating this test failure?

We currently don't support the dry-run deployment for members outside our team. Your changes look good and all of the required checks are passing, so we can move forward with merging.

Thank you again for the contribution!

2023-05-15 18:32 UTC, merged