fix: Table sticky scrollbar dangling when draging the table
cloudscape-design/components pull request #1116
Opened 2023-05-22 12:01 UTC by YueyingLu

### Description

Related links, issue #, if available: n/a

### How has this been tested?

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-25 12:45 UTC, gethinwebster requested changes

2023-05-25 14:29 UTC, YueyingLu commented on src/table/styles.scss
> +  -ms-overflow-style: none; /* Internet Explorer 10+ */
changed

2023-05-25 14:40 UTC, gethinwebster submitted a review, later dismissed

2023-05-26 08:59 UTC, pan-kot submitted a review, later dismissed
Great work!

2023-05-31 09:48 UTC, pan-kot approved these changes

2023-05-31 12:58 UTC, pan-kot approved these changes

2023-05-31 15:09 UTC, pan-kot approved these changes

2023-05-31 15:22 UTC, merged