feat: Update primary link styling and usage
cloudscape-design/components pull request #1405
Opened 2023-08-03 07:41 UTC by gethinwebster

### Description

Updates primary link styling to have clearer affordance (underline instead of bold).

Also updates some components to use primary variant by default
(instead of secondary) where we know that this extra affordance is useful.

Related links, issue #, if available: AWSUI-21365

### How has this been tested?

Checked visual regression tests in dev pipeline, changes are as expected

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-03 14:31 UTC, rubencarvalho commented on src/table/internal.tsx
I think GitHub didn't understand this diff 😅 
Just making sure, we just wrapped the table with the `LinkDefaultVariantContext.Provider`.

2023-08-03 14:34 UTC, gethinwebster commented on src/table/internal.tsx
yup, exactly 😂

2023-08-03 17:10 UTC, rubencarvalho requested changes
Could we add some links to the cards permutations page, so this can be tested in the screenshots?

2023-08-07 07:12 UTC, rubencarvalho approved these changes

2023-08-07 07:14 UTC, merged