chore: Support nested funnels
cloudscape-design/components pull request #1427
Opened 2023-08-09 11:39 UTC by connorlanigan

### Description

This PR adds support for placing funnels inside other funnels (i.e. currently the Form and the Wizard components).
When a Form is placed inside another Form, the inner Form is now ignored.
When a Wizard is placed inside or around a Form, the Wizard now always takes precedence.

Related links, issue #, if available: n/a

### How has this been tested?

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-10 11:53 UTC, johannes-weber requested changes
The changes looks good to me!

The a11y tests are failing on the newly added `pages/funnel-analytics/nested-funnels.page.tsx`. I see it's not used in any of our tests - do we need it as part of the change or was it used for manual testing?

2023-08-10 12:24 UTC, connorlanigan commented
The new dev page is only for manual testing. I had forgotten to label the inputs, I've added them now in the new revision.

2023-08-10 15:06 UTC, johannes-weber approved these changes

2023-08-16 16:04 UTC, connorlanigan commented on src/wizard/__tests__/analytics.test.tsx
> +  test('handles the funnel even if nested inside a single-page funnel', () => {
Good idea, thanks!

2023-08-17 15:51 UTC, johannes-weber approved these changes

2023-08-17 15:52 UTC, merged