feat: Add accessible name to mode switcher in Date range picker
cloudscape-design/components pull request #1616
Opened 2023-10-04 19:58 UTC by Al-Dani

### Description

Mode switcher in Date range picker is a toolbar and, therefore, should have an accessible name that describes it. We need to pass a string to `label` property of the segmented control used for the mode switcher

Related links, issue #, if available: AWSUI-22536

### How has this been tested?

new unit test added

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-09 13:32 UTC, stirache approved these changes

2023-10-11 20:33 UTC, rubencarvalho approved these changes

2023-10-12 11:32 UTC, stirache requested changes

2023-10-12 11:32 UTC, stirache commented on src/date-range-picker/interfaces.ts
> +     * Label of the mode selection group. In the standard view it adds `aria-label` on the group of segments.
Slight grammar tweak: "Label of the mode selection group. In the standard view, it adds 'aria-label' to the group of segments."

2023-10-12 11:54 UTC, stirache approved these changes

2023-10-12 12:30 UTC, rubencarvalho approved these changes

2023-10-12 13:03 UTC, merged