fix: Fix table selections when user selection in 'multi' selection mode when user selects and paginates afterwords
cloudscape-design/components pull request #164
Opened 2022-08-16 09:34 UTC by taheramr

### Description
This solves an issue when the user has a pagination with checkboxes in the table and tries to select an item and then go the next page, in this case the checkbox in the table's header will not be selected and this is not desired.

### How has this been tested?

To test the problem you can go to `light/table/sticky-header-scrollable-container` page and try with/without this change.

[_How did you test to verify your changes?_]

[_How can reviewers test these changes efficiently?_]

[_Check for unexpected visual regressions, see [`CONTRIBUTING.md`](CONTRIBUTING.md#run-visual-regression-tests) for details._]

### Documentation changes

[*Do the changes include any API documentation changes?*]
- [ ] _Yes, this change contains documentation changes._
- [ ] _No._

### Related Links

[*Attach any related links/pull request for this change*]

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- [ ] _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](CONTRIBUTING.md#public-apis)._
- [ ] _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](CONTRIBUTING.md#browsers-support)._
- [ ] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- [ ] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- [ ] _Changes are covered with new/existing unit tests?_
- [ ] _Changes are covered with new/existing integration tests?_
</details>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-16 09:42 UTC, just-boris commented
How about adding a unit test for the new behavior?

2022-08-16 10:04 UTC, abdhalees requested changes
Can we rephrase the commit message to describe what the PR does rather than describing the issue? 

Also can you add a unit test?

2022-08-17 09:44 UTC, abdhalees requested changes

2022-08-17 09:44 UTC, abdhalees commented on src/table/__tests__/selection.test.tsx
> +  test('indetermunate, when there are selected items that do not match the items list', () => {
typo "indetermunate" => indeterminate

2022-08-18 08:21 UTC, abdhalees approved these changes

2022-08-18 08:36 UTC, merged