fix: Chart detail popover should open when focus moves out and in again
cloudscape-design/components pull request #1777
Opened 2023-12-05 12:11 UTC by YueyingLu

### Description

When focus moves out, the popover is closed, see https://github.com/cloudscape-design/components/blob/c17dd790be5b158190eb295036b34da22992098e/src/mixed-line-bar-chart/chart-container.tsx#L392-L410

The highlightedX is not updated at this moment. So when the focus moves back, the popover not show up https://github.com/cloudscape-design/components/blob/c17dd790be5b158190eb295036b34da22992098e/src/mixed-line-bar-chart/chart-container.tsx#L345-L349

 The change opens the Popover when focus moves back.

Related links, issue #AWSUI-24744

### How has this been tested?

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-05 14:49 UTC, abdhalees requested changes
there is a failing integ test

2023-12-14 14:55 UTC, YueyingLu commented on src/internal/components/chart-plot/index.tsx
> +          showPopoverOfHighlightedItem();
The change was covered by integration test.

2023-12-14 14:55 UTC, YueyingLu commented on src/mixed-line-bar-chart/chart-container.tsx
> +      showPopover();
The change is covered by integration test.

2023-12-15 11:30 UTC, abdhalees approved these changes

2023-12-20 10:17 UTC, jperals commented
This component has quite a few state variables that have to be kept in sync, which is prone to bugs like this, so it might be possible to do this by removing logic instead of adding. An alternative fix is to keep `isPopoverOpen` to `true` when focusing out, but only render it if there are highlighted elements, see this POC: https://github.com/cloudscape-design/components/pull/1821/files

2023-12-28 14:18 UTC, YueyingLu commented
> This component has quite a few state variables that have to be kept in sync, which is prone to bugs like this, so it might be possible to do this by removing logic instead of adding. An alternative fix is to keep `isPopoverOpen` to `true` when focusing out, but only render it if there are highlighted elements, see this POC: https://github.com/cloudscape-design/components/pull/1821/files

Thank you for the POC. When tabbing out the chart, the highlightedItem still exists, but the popover should close. This approach will keep the Popover open, even has tabbed out the chart by keyboard.

2023-12-28 16:05 UTC, pan-kot commented
The issue only exists in bar charts but not in area-, line- or pie charts. Why? In all charts there is state that keeps the highlighted element yet no workaround is required. My guess is that we clear the state on blur and a consistent approach is to ensure the same for the bar chart.

2023-12-29 13:58 UTC, pan-kot approved these changes

2023-12-29 14:22 UTC, YueyingLu commented on src/mixed-line-bar-chart/chart-container.tsx
> +      clearHighlightedSeries();
Bar chart will not remember the highlighted item when tab out. However this is not consistent behavior between Bar, Line and Area charts.

2023-12-29 14:23 UTC, merged