feat: Add onClick event for Link component
cloudscape-design/components pull request #2295
Opened 2024-05-27 08:43 UTC by YueyingLu

### Description

Add onClick event for Link component. 

Currently Link has one event: onFollow, which is called when the Link is called without modifier key. Our customer needs an event calls for every onClick to collect metrics. 

Related links, issue #, if available: n/a

### How has this been tested?

 Add unit tests 

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-28 10:02 UTC, gethinwebster requested changes

2024-05-28 10:02 UTC, gethinwebster commented on src/link/internal.tsx
> +      fireNonCancelableEvent(onClick, { altKey, button, ctrlKey, metaKey, shiftKey });
can we add a comment here why this is nonCancelable, so that it doesn't get "fixed" in the future?

2024-05-28 11:55 UTC, gethinwebster submitted a review, later dismissed

2024-05-29 08:05 UTC, georgylobko approved these changes

2024-05-29 08:22 UTC, gethinwebster approved these changes

2024-05-29 09:31 UTC, merged