feat: Add `headerAriaLabel` property to Expandable Section
cloudscape-design/components pull request #318
Opened 2022-09-30 11:47 UTC by timogasda

### Description

Adds a new `headerAriaLabel` property to Expandable Section that adds an explicit `aria-label` to the header button.

This is useful if you have multiple expandable sections with the same title on one page.

### How has this been tested?

Tested manually. Added unit tests.

### Documentation changes

[*Do the changes include any API documentation changes?*]
- [x] _Yes, this change contains documentation changes._
- [ ] _No._

### Related Links

[*Attach any related links/pull request for this change*]

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- [ ] _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](CONTRIBUTING.md#public-apis)._
- [ ] _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](CONTRIBUTING.md#browsers-support)._
- [ ] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- [ ] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- [ ] _Changes are covered with new/existing unit tests?_
- [ ] _Changes are covered with new/existing integration tests?_
</details>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-30 12:04 UTC, timogasda commented
Visual Regression Tests failures are expected because of added permutations.

2022-10-04 07:02 UTC, johannes-weber submitted a review, later dismissed
LGTM.

2022-10-05 14:37 UTC, stirache requested changes

2022-10-05 14:37 UTC, stirache commented on src/__tests__/__snapshots__/documenter.test.ts.snap
> +It should be used to assign unique labels when there are multiple expandable sections with the same header text on one page.",
```suggestion
Use to assign unique labels when there are multiple expandable sections with the same header text on one page.
```

2022-10-05 14:37 UTC, stirache commented on src/expandable-section/interfaces.ts
> +   * It should be used to assign unique labels when there are multiple expandable sections with the same header text on one page.
```suggestion
Use to assign unique labels when there are multiple expandable sections with the same header text on one page.
```

2022-10-05 16:32 UTC, timogasda commented on src/__tests__/__snapshots__/documenter.test.ts.snap
> +It should be used to assign unique labels when there are multiple expandable sections with the same header text on one page.",
Sounds great! Changed it

2022-10-05 16:34 UTC, stirache approved these changes

2022-10-06 07:16 UTC, gethinwebster approved these changes

2022-10-06 07:18 UTC, merged