fix(expandable-section): Reduce activation area
cloudscape-design/components pull request #389
Opened 2022-10-18 16:49 UTC by FlorianDr

### Description

Reduces activation area of expandable section to icon + text. This also moves the conditional header `border-bottom` to the content. It is only disabled if there is content.  

### How has this been tested?

Screenshots

### Documentation changes

[*Do the changes include any API documentation changes?*]
- [ ] _Yes, this change contains documentation changes._
- [X] _No._

### Related Links

[*Attach any related links/pull request for this change*]

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- [ ] _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](CONTRIBUTING.md#public-apis)._
- [ ] _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](CONTRIBUTING.md#browsers-support)._
- [ ] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- [ ] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- [ ] _Changes are covered with new/existing unit tests?_
- [ ] _Changes are covered with new/existing integration tests?_
</details>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-19 11:55 UTC, timogasda commented
Why are we doing this? Why is it a "fix"?

And do we not think this is potentially a UX breaking change and/or regression?

2022-10-19 12:29 UTC, taheramr requested changes

2022-10-19 12:29 UTC, taheramr commented on src/expandable-section/styles.scss
> +    border-top: awsui.$border-divider-section-width solid awsui.$color-border-divider-default;
The PR looks good but removing the `border-bottom` from the toggle and adding it to the content removes the border transitions

2022-10-24 13:02 UTC, FlorianDr commented
> Could you explain a bit more why are we doing this? Why is it a "fix"?
> 
> And do we not think this is potentially a UX breaking change and/or regression?

Resolved in person.

2022-10-25 15:18 UTC, closed without merging