Remove date-picker/calendar calendarHasFocus as unneeded
cloudscape-design/components pull request #90
Opened 2022-07-29 10:49 UTC by pan-kot

### Description

Refactor date picker calendar by removing unneeded variable.

### How has this been tested?

Existing tests -- no behaviour changes expected. Added an integration test to cover date selection.

### Documentation changes

[*Do the changes include any API documentation changes?*]
- [ ] _Yes, this change contains documentation changes._
- [x] _No._

### Related Links

[*Attach any related links/pull request for this change*]

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- [ ] _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](CONTRIBUTING.md#public-apis)._
- [ ] _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](CONTRIBUTING.md#browsers-support)._
- [ ] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/).

#### Security

- [ ] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts).

#### Testing

- [ ] _Changes are covered with new/existing unit tests?_
- [ ] _Changes are covered with new/existing integration tests?_
</details>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-29 16:29 UTC, johannes-weber requested changes

2022-07-29 16:29 UTC, johannes-weber commented on src/date-picker/calendar/header/button/index.tsx
> +    tabIndex: 0,
Minor: this line can be removed - the default value of `tabindex` is 0 when not specified.

2022-08-01 10:17 UTC, johannes-weber approved these changes

2022-08-01 10:56 UTC, pan-kot commented
Rebased with main

2022-08-01 11:10 UTC, johannes-weber approved these changes
LGTM.

2022-08-01 11:11 UTC, merged