fix: Standardize focus behavior when removing tags
cloudscape-design/components pull request #903
Opened 2023-03-29 15:50 UTC by gethinwebster

### Description

Standardize focus handling when removing tags in TagEditor: focus another tag when possible, otherwise the 'Add tag' button.

Related links, issue #, if available: AWSUI-20696

### How has this been tested?

New unit tests

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-29 16:29 UTC, timogasda approved these changes

2023-03-29 16:29 UTC, timogasda commented on src/attribute-editor/interfaces.ts
> +     * Focuses the 'add' button. Use this, for example, after a user removes the last row.
minor/writing: They should probably either both say "remove button" and "add button", or "'remove' button" and "'add' button"

2023-03-30 08:28 UTC, stirache requested changes

2023-03-30 08:37 UTC, timogasda approved these changes

2023-03-31 09:06 UTC, merged